//Copyright © 2022 <Beyley Thomas>
//
//Permission is hereby granted, free of charge, to any person obtaining a
//copy of this software and associated documentation files (the “Software”),
//to deal in the Software without restriction, including without limitation the rights to
//use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
//and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
//INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
//IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
//WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

using EvDevSharp.Enums;
using Silk.NET.Input;

namespace Furball.Engine.Engine.Helpers;

public static class EvDevConversionHelpers {
    public static Key ToSilk(this EvDevKeyCode k) {
        return k switch {
            EvDevKeyCode.KeyEsc        => Key.Escape,
            EvDevKeyCode.Key1          => Key.Number1,
            EvDevKeyCode.Key2          => Key.Number2,
            EvDevKeyCode.Key3          => Key.Number3,
            EvDevKeyCode.Key4          => Key.Number4,
            EvDevKeyCode.Key5          => Key.Number5,
            EvDevKeyCode.Key6          => Key.Number6,
            EvDevKeyCode.Key7          => Key.Number7,
            EvDevKeyCode.Key8          => Key.Number8,
            EvDevKeyCode.Key9          => Key.Number9,
            EvDevKeyCode.Key0          => Key.Number0,
            EvDevKeyCode.KeyMinus      => Key.Minus,
            EvDevKeyCode.KeyEqual      => Key.Equal,
            EvDevKeyCode.KeyBackspace  => Key.Backspace,
            EvDevKeyCode.KeyTab        => Key.Tab,
            EvDevKeyCode.KeyQ          => Key.Q,
            EvDevKeyCode.KeyW          => Key.W,
            EvDevKeyCode.KeyE          => Key.E,
            EvDevKeyCode.KeyR          => Key.R,
            EvDevKeyCode.KeyT          => Key.T,
            EvDevKeyCode.KeyY          => Key.Y,
            EvDevKeyCode.KeyU          => Key.U,
            EvDevKeyCode.KeyI          => Key.I,
            EvDevKeyCode.KeyO          => Key.O,
            EvDevKeyCode.KeyP          => Key.P,
            EvDevKeyCode.KeyLeftbrace  => Key.LeftBracket,
            EvDevKeyCode.KeyRightbrace => Key.RightBracket,
            EvDevKeyCode.KeyEnter      => Key.Enter,
            EvDevKeyCode.KeyLeftctrl   => Key.ControlLeft,
            EvDevKeyCode.KeyA          => Key.A,
            EvDevKeyCode.KeyS          => Key.S,
            EvDevKeyCode.KeyD          => Key.D,
            EvDevKeyCode.KeyF          => Key.F,
            EvDevKeyCode.KeyG          => Key.G,
            EvDevKeyCode.KeyH          => Key.H,
            EvDevKeyCode.KeyJ          => Key.J,
            EvDevKeyCode.KeyK          => Key.K,
            EvDevKeyCode.KeyL          => Key.L,
            EvDevKeyCode.KeySemicolon  => Key.Semicolon,
            EvDevKeyCode.KeyApostrophe => Key.Apostrophe,
            EvDevKeyCode.KeyGrave      => Key.GraveAccent,
            EvDevKeyCode.KeyLeftshift  => Key.ShiftLeft,
            EvDevKeyCode.KeyBackslash  => Key.BackSlash,
            EvDevKeyCode.KeyZ          => Key.Z,
            EvDevKeyCode.KeyX          => Key.X,
            EvDevKeyCode.KeyC          => Key.C,
            EvDevKeyCode.KeyV          => Key.V,
            EvDevKeyCode.KeyB          => Key.B,
            EvDevKeyCode.KeyN          => Key.N,
            EvDevKeyCode.KeyM          => Key.M,
            EvDevKeyCode.KeyComma      => Key.Comma,
            EvDevKeyCode.KeyDot        => Key.Period,
            EvDevKeyCode.KeySlash      => Key.Slash,
            EvDevKeyCode.KeyRightshift => Key.ShiftRight,
            EvDevKeyCode.KeyLeftalt    => Key.AltLeft,
            EvDevKeyCode.KeySpace      => Key.Space,
            EvDevKeyCode.KeyCapslock   => Key.CapsLock,
            EvDevKeyCode.KeyF1         => Key.F1,
            EvDevKeyCode.KeyF2         => Key.F2,
            EvDevKeyCode.KeyF3         => Key.F3,
            EvDevKeyCode.KeyF4         => Key.F4,
            EvDevKeyCode.KeyF5         => Key.F5,
            EvDevKeyCode.KeyF6         => Key.F6,
            EvDevKeyCode.KeyF7         => Key.F7,
            EvDevKeyCode.KeyF8         => Key.F8,
            EvDevKeyCode.KeyF9         => Key.F9,
            EvDevKeyCode.KeyF10        => Key.F10,
            EvDevKeyCode.KeyNumlock    => Key.NumLock,
            EvDevKeyCode.KeyScrolllock => Key.ScrollLock,
            EvDevKeyCode.KeyKp7        => Key.Keypad7,
            EvDevKeyCode.KeyKp8        => Key.Keypad8,
            EvDevKeyCode.KeyKp9        => Key.Keypad9,
            EvDevKeyCode.KeyKpminus    => Key.KeypadSubtract,
            EvDevKeyCode.KeyKp4        => Key.Keypad4,
            EvDevKeyCode.KeyKp5        => Key.Keypad5,
            EvDevKeyCode.KeyKp6        => Key.Keypad6,
            EvDevKeyCode.KeyKpplus     => Key.KeypadAdd,
            EvDevKeyCode.KeyKp1        => Key.Keypad1,
            EvDevKeyCode.KeyKp2        => Key.Keypad2,
            EvDevKeyCode.KeyKp3        => Key.Keypad3,
            EvDevKeyCode.KeyKp0        => Key.Keypad0,
            EvDevKeyCode.KeyKpdot      => Key.KeypadDecimal,
            EvDevKeyCode.KeyF11        => Key.F11,
            EvDevKeyCode.KeyF12        => Key.F12,
            EvDevKeyCode.KeyKpenter    => Key.KeypadEnter,
            EvDevKeyCode.KeyRightctrl  => Key.ControlRight,
            EvDevKeyCode.KeyKpslash    => Key.KeypadDivide,
            EvDevKeyCode.KeyRightalt   => Key.AltRight,
            EvDevKeyCode.KeyHome       => Key.Home,
            EvDevKeyCode.KeyUp         => Key.Up,
            EvDevKeyCode.KeyPageup     => Key.PageUp,
            EvDevKeyCode.KeyLeft       => Key.Left,
            EvDevKeyCode.KeyRight      => Key.Right,
            EvDevKeyCode.KeyEnd        => Key.End,
            EvDevKeyCode.KeyDown       => Key.Down,
            EvDevKeyCode.KeyPagedown   => Key.PageDown,
            EvDevKeyCode.KeyInsert     => Key.Insert,
            EvDevKeyCode.KeyDelete     => Key.Delete,
            EvDevKeyCode.KeyKpequal    => Key.KeypadEqual,
            EvDevKeyCode.KeyPause      => Key.Pause,
            EvDevKeyCode.KeyLeftmeta   => Key.SuperLeft,
            EvDevKeyCode.KeyRightmeta  => Key.SuperRight,
            EvDevKeyCode.KeyF13        => Key.F13,
            EvDevKeyCode.KeyF14        => Key.F14,
            EvDevKeyCode.KeyF15        => Key.F15,
            EvDevKeyCode.KeyF16        => Key.F16,
            EvDevKeyCode.KeyF17        => Key.F17,
            EvDevKeyCode.KeyF18        => Key.F18,
            EvDevKeyCode.KeyF19        => Key.F19,
            EvDevKeyCode.KeyF20        => Key.F20,
            EvDevKeyCode.KeyF21        => Key.F21,
            EvDevKeyCode.KeyF22        => Key.F22,
            EvDevKeyCode.KeyF23        => Key.F23,
            EvDevKeyCode.KeyF24        => Key.F24,
            EvDevKeyCode.KeyPrint      => Key.PrintScreen,
            EvDevKeyCode.KeyNumeric0   => Key.Number0,
            EvDevKeyCode.KeyNumeric1   => Key.Number1,
            EvDevKeyCode.KeyNumeric2   => Key.Number2,
            EvDevKeyCode.KeyNumeric3   => Key.Number3,
            EvDevKeyCode.KeyNumeric4   => Key.Number4,
            EvDevKeyCode.KeyNumeric5   => Key.Number5,
            EvDevKeyCode.KeyNumeric6   => Key.Number6,
            EvDevKeyCode.KeyNumeric7   => Key.Number7,
            EvDevKeyCode.KeyNumeric8   => Key.Number8,
            EvDevKeyCode.KeyNumeric9   => Key.Number9,
            _                          => Key.Unknown
        };
    }
}
